export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_ALL_LIST_REQUEST = 'PRODUCT_ALL_LIST_REQUEST'
export const PRODUCT_ALL_LIST_SUCCESS = 'PRODUCT_ALL_LIST_SUCCESS'
export const PRODUCT_ALL_LIST_FAIL = 'PRODUCT_ALL_LIST_FAIL'

export const REVIEW_ALL_LIST_REQUEST = 'REVIEW_ALL_LIST_REQUEST'
export const REVIEW_ALL_LIST_SUCCESS = 'REVIEW_ALL_LIST_SUCCESS'
export const REVIEW_ALL_LIST_FAIL = 'REVIEW_ALL_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'


export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST'
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS'
export const REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'


export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const REVIEW_UPDATE_REQUEST = 'REVIEW_UPDATE_REQUEST'
export const REVIEW_UPDATE_SUCCESS = 'REVIEW_UPDATE_SUCCESS'
export const REVIEW_UPDATE_FAIL = 'REVIEW_UPDATE_FAIL'
export const REVIEW_UPDATE_RESET = 'REVIEW_UPDATE_RESET'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

export const PRODUCT_RANDOM_REQUEST = 'PRODUCT_RANDOM_REQUEST'
export const PRODUCT_RANDOM_SUCCESS = 'PRODUCT_RANDOM_SUCCESS'
export const PRODUCT_RANDOM_FAIL = 'PRODUCT_RANDOM_FAIL'

export const PRODUCT_CATEGORY_LIST_REQUEST = 'PRODUCT_CATEGORY_LIST_REQUEST';
export const PRODUCT_CATEGORY_LIST_SUCCESS = 'PRODUCT_CATEGORY_LIST_SUCCESS';
export const PRODUCT_CATEGORY_LIST_FAIL = 'PRODUCT_CATEGORY_LIST_FAIL';

export const PRODUCT_ID_NAME_REQUEST = 'PRODUCT_ID_NAME_REQUEST';
export const PRODUCT_ID_NAME_SUCCESS = 'PRODUCT_ID_NAME_SUCCESS';
export const PRODUCT_ID_NAME_FAIL = 'PRODUCT_ID_NAME_FAIL';

export const SENTIMENT_CIRCLE_CHART_REQUEST = 'SENTIMENT_CIRCLE_CHART_REQUEST';
export const SENTIMENT_CIRCLE_CHART_SUCCESS = 'SENTIMENT_CIRCLE_CHART_SUCCESS';
export const SENTIMENT_CIRCLE_CHART_FAIL = 'SENTIMENT_CIRCLE_CHART_FAIL';

export const SENTIMENT_LINE_CHART_REQUEST = 'SENTIMENT_LINE_CHART_REQUEST';
export const SENTIMENT_LINE_CHART_SUCCESS = 'SENTIMENT_LINE_CHART_SUCCESS';
export const SENTIMENT_LINE_CHART_FAIL = 'SENTIMENT_LINE_CHART_FAIL';

export const SENTIMENT_BAR_CHART_REQUEST = 'SENTIMENT_BAR_CHART_REQUEST';
export const SENTIMENT_BAR_CHART_SUCCESS = 'SENTIMENT_BAR_CHART_SUCCESS';
export const SENTIMENT_BAR_CHART_FAIL = 'SENTIMENT_BAR_CHART_FAIL';

export const SIMILAR_WORD_CLOUD_REQUEST = 'SIMILAR_WORD_CLOUD_REQUEST';
export const SIMILAR_WORD_CLOUD_SUCCESS = 'SIMILAR_WORD_CLOUD_SUCCESS';
export const SIMILAR_WORD_CLOUD_FAIL = 'SIMILAR_WORD_CLOUD_FAIL';

export const USER_BUY_PRODUCT_REQUEST = 'USER_BUY_PRODUCT_REQUEST';
export const USER_BUY_PRODUCT_SUCCESS = 'USER_BUY_PRODUCT_SUCCESS';
export const USER_BUY_PRODUCT_FAIL = 'USER_BUY_PRODUCT_FAIL';



